### ISSUE TITLE
Import Watchlist from IMDb to trakt.tv

### ISSUE THREAD

**Issue by japso** [damienhaynes/TraktRater#10]
I also keep a watchlist at IMDb. The watchlist can be exported from the IMDb website as a csv file.

I just looked at the watchlist csv file and it has exactly the same structure (i.e., columns) as the ratings csv file.

I'd appreciate it very much if your program could be extended to also support the import of a watchlist csv file to trakt.tv.

**Comment by ahmadfaridi** [comment]
I am facing login issue every time i try to import IMDB rating list

**Comment by damienhaynes** [comment]
You wont be able to import from IMDb again until next release, the site changed the format of the CSV files. Also if you are having logon issues you need to switch to PinCode auth.

**Comment by ahmadfaridi** [comment]
@damienhaynes i have tried both login methods but it failed. and any idea for expected release date?
