### ISSUE TITLE
Unable to import from IMDB using scraper nor CSV

### ISSUE THREAD

**Issue by yitzhaq** [damienhaynes/TraktRater#102]
Hi there,

I am unfortunately having no luck importing my watchlist from IMDB, using neither the CSV import nor the scraper. I've made my watchlist public, and accessing the same URL unauthenticated as found in the log file results in a viewable list (so I know username is correct etc), yet 0 entries are imported where there should be 200+. Looking at the log it seems TraktRater is getting back a 403 from IMDB, even though a browser does not, which is likely the reason. Time to consider some UA spoofing, maybe? Also, and unrelated, if you're able to support HTTPS, it might be worthwhile switching to that over HTTP.

Using the CSV importer I get the following error:

2019-08-24 14:07:03.079 [INFO] [][01]: Reading IMDb watchlist export...
2019-08-24 14:07:03.094 [ERR ] [][09]: Error parsing 'C:\WATCHLIST.csv'. Exception = 'The conversion cannot be performed.', Stack = '   at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(TypeConverterOptions options, String text)
   at CsvHelper.TypeConversion.SingleConverter.ConvertFromString(TypeConverterOptions options, String text)
   at lambda_method(Closure )
   at CsvHelper.CsvReader.<GetRecords>d__65`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TraktRater.Sites.IMDb.ParseCsvFile[T](String aFilename, CsvConfiguration aConfig)'
2019-08-24 14:07:03.094 [ERR ] [][01]: Failed to parse IMDb watchlist file!

CSV looks like this:

Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
1,tt1521198,2015-01-30,2015-01-30,,DeLorean - Living the Dream,https://www.imdb.com/title/tt1521198/,movie,,,,"Documentary, Biography, History",,,Jordan Livingston,,
2,tt2442080,2015-11-08,2015-11-08,,Chuck Norris vs. Communism,https://www.imdb.com/title/tt2442080/,movie,7.5,78,2015,"Documentary, Comedy, History, Thriller",1803,2015-01-23,Ilinca Calugareanu,,
3,tt3620088,2015-12-30,2015-12-30,,Celluloid Wizards in the Video Wasteland: The Saga of Empire Pictures,https://www.imdb.com/title/tt3620088/,movie,,,,Documentary,,,Daniel Griffith,, 

[..]

TIA

**Comment by damienhaynes** [comment]
I converted your content to a CSV and ran an import, it seemed to parse fine and send to trakt as:

{
  "movies": [
    {
      "ids": {
        "imdb": "tt1521198"
      },
      "title": "DeLorean - Living the Dream",
      "year": null
    },
    {
      "ids": {
        "imdb": "tt2442080"
      },
      "title": "Chuck Norris vs. Communism",
      "year": 2015
    },
    {
      "ids": {
        "imdb": "tt3620088"
      },
      "title": "Celluloid Wizards in the Video Wasteland: The Saga of Empire Pictures",
      "year": null
    }
  ]
}

**Comment by damienhaynes** [comment]
Was that the full contents?

**Comment by hgN1337** [comment]
same issue here:

[WATCHLIST.zip](https://github.com/damienhaynes/TraktRater/files/3552531/WATCHLIST.zip)

**Comment by damienhaynes** [comment]
Thanks @hgN1337 but I had no problem parsing your file as well!

Can you attach your log to see if its the same issue as above.

Is the rating file parsing correctly, or is it just watchlist?

**Comment by damienhaynes** [comment]
I've added some handling to ignore lines it can't read plus write a log message for the offending row. See if this helps tracking down the issue.
[TraktRater.zip](https://github.com/damienhaynes/TraktRater/files/3553212/TraktRater.zip)

**Comment by hgN1337** [comment]
Hi thanks for the fast response. Unfortunately it dont work with your attached version.
[20190901_110953.log](https://github.com/damienhaynes/TraktRater/files/3563295/20190901_110953.log)
(i removed the token lines ..)

**Comment by damienhaynes** [comment]
hi @hgN1337 , can I ask what your regional settings are set to if using Windows?

**Comment by damienhaynes** [comment]
I think the attached should fix the issue, I set the culture to "en-US" when reading the file as the decimal seperator is ".", I'm, guessing you use "," seperator.
[TraktRater.zip](https://github.com/damienhaynes/TraktRater/files/3563366/TraktRater.zip)

**Comment by yitzhaq** [comment]
Thanks for the fix - I can confirm that the attached version successfully imports my watchlist. My locale does indeed use "," as a separator.
IMDB scraping still results in a 403, but this is a lesser issue (and perhaps deserving of a separate report) as long as the CSV import now works.

**Comment by hgN1337** [comment]
Hi, thanks this worked for me and yes i use a german Windows

**Comment by damienhaynes** [comment]
Great, thanks for confirming. Yes, the webscrape will need a separate report, I did not code up that but will take a look, it's not surprising as a website change would cause it to break.
