### ISSUE TITLE
Support for Letterboxd custom lists

### ISSUE THREAD

**Issue by nigelwarning** [damienhaynes/TraktRater#104]
Would love the function to import custom lists for letterboxd to trakt

**Comment by nigelwarning** [comment]
Hope this will be inplemented one day. Would love to import some Letterboxd lists in a custom Trakt list :D

**Comment by damienhaynes** [comment]
Thanks for your suggestion and donation @nigelwarning, I will look into what is involved. It's been a while since I looked at the Letterboxd.

**Comment by nigelwarning** [comment]
Thanks for the fast anwser!

**Comment by damienhaynes** [comment]
Hi @nigelwarning, here is a test binary for custom list import from Letterboxd. 

I used the csv filename as the List name (not the list name inside the csv).
[TraktRater_v2.3.9_Beta.exe.zip](https://github.com/damienhaynes/TraktRater/files/4015758/TraktRater_v2.3.9_Beta.exe.zip)

**Comment by nigelwarning** [comment]
I did a import of a list and it worked!

**Comment by damienhaynes** [comment]
nice, thanks for the confirmation.

**Comment by nigelwarning** [comment]
Thanks for the work :D
