### ISSUE TITLE
IMDB TO TRACK - ERROR READING

### ISSUE THREAD

**Issue by NBSDEVApp** [damienhaynes/TraktRater#107]
Hi,
I have this error when i try to import this custom list to my trakt.
I have a new list created in my trakt, but the list is empty.
I have try with these two list: https://www.imdb.com/list/ls068774556
https://www.imdb.com/list/ls064874799/

Thanks for help

`2019-11-20 11:33:20.879 [ERR ] [][03]: Error reading row 'Row: '18' (1 based)
Type: 'TraktRater.Sites.API.IMDb.IMDbListItem'
Field Index: '-1' (0 based)
'
2019-11-20 11:33:20.879 [ERR ] [][03]: Error reading row 'Row: '19' (1 based)
Type: 'TraktRater.Sites.API.IMDb.IMDbListItem'
Field Index: '-1' (0 based)
'
2019-11-20 11:33:20.879 [ERR ] [][03]: Error reading row 'Row: '20' (1 based)
Type: 'TraktRater.Sites.API.IMDb.IMDbListItem'
Field Index: '-1' (0 based)
'
2019-11-20 11:33:20.880 [ERR ] [][03]: Error reading row 'Row: '21' (1 based)
Type: 'TraktRater.Sites.API.IMDb.IMDbListItem'
Field Index: '-1' (0 based)`

**Comment by damienhaynes** [comment]
Thanks, I will download the CSVs and see what is wrong.

**Comment by NBSDEVApp** [comment]
Do you have find the issue ?

**Comment by NBSDEVApp** [comment]
Hi, Do you have try ?

**Comment by NBSDEVApp** [comment]
@damienhaynes You have forget me Sir ?

**Comment by damienhaynes** [comment]
Hi @NBSDEVApp, sorry to take so long to get back to you. I promise to look soon, just been too busy with higher priority work.

**Comment by damienhaynes** [comment]
Okay, I can reproduce your problem and about to fix. Stay tuned for a new release.

**Comment by damienhaynes** [comment]
New release available:
https://github.com/damienhaynes/TraktRater/releases/tag/2.3.8

**Comment by NBSDEVApp** [comment]
Thanks you 👍
