### ISSUE TITLE
imdb csv creation date is not considerated

### ISSUE THREAD

**Issue by hoobtron** [damienhaynes/TraktRater#108]
Hi Damien, thanks fot the app!

I used TraktRater (with Mono on macOS) to import my IMDB watchlist (2000+) and ratings to trakt.tv.
As a trakt client I use the iOS app Watcht. If I go to the "Watch List" tab of this app, I realised after the import, that the creation dates of the watchlist movies is not taken over into trakt. 

Right now all my imported movies have the same date/time (of the import)  :(

The date of each movie (when I added it to IMDB) is stored in the 3rd column of the WATCHLIST.csv as "Created".
So, can you interpret this also on import please?
(would be important to use it for sorting with "Added Date")

**Comment by damienhaynes** [comment]
Hi @hoobtron, this is a deficiency of the API:
https://trakt.docs.apiary.io/#reference/sync/add-to-watchlist/add-items-to-watchlist

It does not have support for date added unfortunately.

**Comment by hoobtron** [comment]
meeh, I see.. alright, thanks
