### ISSUE TITLE
Import to trakt from imdb limited by batch import size

### ISSUE THREAD

**Issue by jezaldanluthar** [damienhaynes/TraktRater#110]
Im using traktrater v2.3.9.0. 

I am trying to import around 10k movies to trakt by using a .csv from imdb. 

I am limited by the Batch import size meaning if I set it to 50 it will only import 50 movies to trakt. If I set it to 1000 it will only import 1000 movies from the imdb.csv.

Not sure what I am doing wrong, but any advice is appreciated. If we find a solution I am happy to donate to the project. Thank you

**Comment by jezaldanluthar** [comment]
Take this list for example. Im only able to import 49 movies if I set my batch import size to 50. Im out of ideas and would really appreciate any input on this.

[test.zip](https://github.com/damienhaynes/TraktRater/files/4302011/test.zip)

**Comment by damienhaynes** [comment]
Thanks for reporting, I will take a look shortly.

**Comment by damienhaynes** [comment]
I had a look at your CSV file and does not appear to have any ratings, are you trying to import as a watchlist?

**Comment by jezaldanluthar** [comment]
@damienhaynes I am trying to import it as a custom list. Thanks for the fast response! I really appreciate it. Does it import the list fine for you?

**Comment by damienhaynes** [comment]
It seems your CSV file is bad, it duplicates each movie for every 50 items.

**Comment by jezaldanluthar** [comment]
I am sorry to have bothered you with this when the mistake was on my end. Will look into it and send a donation along your way. Thanks for your help

**Comment by damienhaynes** [comment]
No worries, and good luck.
