### ISSUE TITLE
How do I run it

### ISSUE THREAD

**Issue by flippyinavder** [damienhaynes/TraktRater#128]
i download these files and I get a big zipped file of stuff, but I don't know how to actually run the main thing to get started

**Comment by damienhaynes** [comment]
Hi @flippyinavder, perhaps you download the wrong file. There should only be a single excutable in the packaged zip:
https://github.com/damienhaynes/TraktRater/releases/download/2.3.10/TraktRater_v2.3.10.2.exe.7z

**Comment by flippyinavder** [comment]
when I download it it comes out as a .exe.7z

and it shows a blank piece of paper as the icon, I cant open it with anything

**Comment by damienhaynes** [comment]
the .7z file extensions open with the archive utility 7zip: https://www.7-zip.org/download.html

**Comment by flippyinavder** [comment]
okay i downloade the one for 32 for windows cause that's how many bits my laptop is, I drag and drop the file

but it either gives me an install option which does nothing or it makes me search for the trakt file, and for some reason I cant find it even though I put it in an easily identifiable folder

**Comment by flippyinavder** [comment]
Still having trouble heh

**Comment by damienhaynes** [comment]
Very weird you can't get it running, maybe some screenshots of your process/workflow might help me better understand what's happening.

**Comment by flippyinavder** [comment]
Well I'm in bed for the night so ill have ti get back to you tomorrow, ill
definitely send you screen recorder footage over email though, if it'll fit

**Comment by flippyinavder** [comment]
https://user-images.githubusercontent.com/82181602/114585381-31fad580-9c49-11eb-89ba-f248b9b0a79d.mp4

i recorded the bandicam of me trying to do whatever XD

**Comment by flippyinavder** [comment]
anything look familar?

**Comment by flippyinavder** [comment]
hey man anything look familair, i dont know if you were able to see my screen cap video at all [](url)
![help 3](https://user-images.githubusercontent.com/82181602/116173131-a6198c80-a6d1-11eb-83e1-9544eb18cae1.PNG)

**Comment by damienhaynes** [comment]
Appologies @flippyinavder, it totally slipped my mind. I will take a look tonight if I can find the time.

**Comment by flippyinavder** [comment]
thanks man

**Comment by damienhaynes** [comment]
Follow these steps:
1. Double click on the 7z1900 exe;
2. By default the destination folder is `C:\Program Files\7-Zip\`, you can change this if you want to, but just leave it for now;
3. Press OK
4. This will install 7z to your computer to `C:\Program Files\7-Zip\`
5. Go to `C:\Program Files\7-Zip\` in File explorer
6. Double click on file `7zFM.exe`
7. This will open 7z user interface window
8. With-in this window, search for where you downloaded the traktrater 7z file e.g. copy to C:\Temp or something for now
9. From the 7z user interface, browse to c:\temp and double click on downloaded traktrater file `TraktRater_v2.3.10.2.exe.7z`
10. Select `TraktRater_v2.3.10.2.exe` file, drag-drop to c:\temp or other location on disk

Note: this is a very verbose way of doing the steps but should work

**Comment by damienhaynes** [comment]
![image](https://user-images.githubusercontent.com/680624/116312645-10285380-a7f0-11eb-9858-5843100f1a69.png)
After double click file within 7z:
![image](https://user-images.githubusercontent.com/680624/116312688-1d454280-a7f0-11eb-8537-2757181dc48c.png)

**Comment by flippyinavder** [comment]
I got em
Thanks a bunch man
