### ISSUE TITLE
Is it possible to access a list of the movies/TV shows that were unable to get imported to Trakt.tv?

### ISSUE THREAD

**Issue by NomaanMalick** [damienhaynes/TraktRater#132]

**Comment by damienhaynes** [comment]
Yes, they should be listed in your log file.

**Comment by NomaanMalick** [comment]
I can't find them. Can you help me with that?

![2021-06-22 00_51_22-](https://user-images.githubusercontent.com/46681247/122816310-2f28fa80-d2f4-11eb-9bc5-e170dfc0c6b0.png)

**Comment by damienhaynes** [comment]
If you look at the line above your highlighted "Unable" keyword, search for where it says "not_found" and inspect the movies after that.

**Comment by NomaanMalick** [comment]
The "not_found" line does not seem to include any information to identify the films/TV shows skipped by TraktRater.
https://user-images.githubusercontent.com/46681247/122898305-6638f380-d368-11eb-92e7-032cacdc1e62.mp4

**Comment by damienhaynes** [comment]
I see what you mean, this appears to be a bug in the Trakt API where it is not returning the movie titles/year for movies not found. It seems to only return the rated/watched date and the ID of the movie (if provided, but in the case of letterbox it doesn't).

The only thing I can think of to help you track which ones didn't match, is to use the Rated/Watched date in the `not_found` list and search for those dates in the `Post` list (log lines above)...with any luck you will only get a single match and find your movie.

Another thing you can try is to re-run the import, TraktRater should compare what movies you have already rated/watched online from your first import, and then only try to import the others. The `others` in this context would be the ones that failed in your first run.

Hope that helps.

**Comment by damienhaynes** [comment]
Closing this issue but please re-open if my last post was not clear nor helped.
