### ISSUE TITLE
imdb to trakt problem

### ISSUE THREAD

**Issue by gokhanko** [damienhaynes/TraktRater#142]
When I try to import custom list from imdb to trakt I get the error log on the attached file. How can I solve it
[20220430_120703.log](https://github.com/damienhaynes/TraktRater/files/8596508/20220430_120703.log)
?

**Comment by damienhaynes** [comment]
Please attach the csv for inspection.

**Comment by gokhanko** [comment]
[1000.csv](https://github.com/damienhaynes/TraktRater/files/8596572/1000.csv)
here it is

**Comment by jsnarredondo** [comment]
> [1000.csv](https://github.com/damienhaynes/TraktRater/files/8596572/1000.csv) here it is

I'm having the same issue. Were you able to get it working?

**Comment by gokhanko** [comment]
Yes, it’s because of regional settings on windows I guess. I changed it to US and it worked after that. I needed to change language to English also but it’s not necessary maybe.

**Comment by damienhaynes** [comment]
Thanks, @gokhanko, it probably has to do with parsing columns delimited with a comma. Perhaps in your region, commas are used as decimal separators e.g. in ratings 7,5-> 7.5. In those particular cases, the app might be treating it as a new column.

Anyway, that is just a guess. I can look into ways to make it more region aware.

**Comment by damienhaynes** [comment]
It should hopefully be resolved in 2.3.15.
