### ISSUE TITLE
[Feature Request] Overwrite Trakt ratings when importing

### ISSUE THREAD

**Issue by zotoro** [damienhaynes/TraktRater#159]
I'm hoping to see if there's a way to overwrite Trakt ratings with the ratings from the selected import source. 

I used to use Trakt for ratings a while ago but then switched to Criticker. When importing the CSV file from Criticker, any unrated items are properly rated to match my Criticker rating, however Trakt items with a pre-existing rating seem to be skipped and not updated to my Criticker rating.

Is there a way that either already exists or can be easily implemented to overwrite existing ratings on Trakt?

I have over 2000 ratings on Trakt, so doing this manually isn't feasible and I'd like to not have to create a new Trakt account from scratch.

**Comment by damienhaynes** [comment]
There is no option to overwrite, but there is option to reset items which you could do first?

**Comment by zotoro** [comment]
I'm an idiot and somehow didn't see that before lol. Thanks for pointing out the maintenance function under options. Appreciate it.

**Comment by damienhaynes** [comment]
Hopefully that can workaround your issue.

**Comment by zotoro** [comment]
Yup, that worked great. Thanks!
