### ISSUE TITLE
Import from IMDb means I have a load of weird/random things I have never seen in trakt.tv

### ISSUE THREAD

**Issue by robme** [damienhaynes/TraktRater#160]
First I tried using the web scrape, and it said it was successful but nothing was imported, so I guess that doesn't work currently.

Next I exported my ratings from IMDb to a CSV and after the import the log is full of this:

> Unable to sync ratings for X movies as they're not found on trakt.tv!

where X is a number.

But then after looking at my watch history on trakt.tv, it's full of random things I have never seen or heard of. It looks like it has taken the titles of TV show episodes, and then looked up a movie of the same name, and found something like an animation with a runtime of 1 minute which I have no idea what it even is and I am the only person to have watched it on trakt. Or 1980s Bollywood movies etc. Just anything that has the same name as the TV episode.

I'm surprised that it just uses the title to look it up, I would think that's a very unreliable way of doing it since so many TV show episodes will have 1 word or simple titles. Have I done something wrong? Why is it only importing everything as movies?

**Comment by robme** [comment]
Do you know is there a way to delete or reset everything because trakt.tv says I have never watched a TV show, but I have watched a very unusual and eclectic mix of rare and unknown foreign movies.

**Comment by damienhaynes** [comment]
Hi @robme, the webscrape could definitely go wrong due to website changes thus the recommended option is the CSV file import.

It's odd that you experienced issues with that unless IMDb have changed the format recently. It definitely should use IMDb ID as the lookup (at least for movies), are you imports for tv shows by any chance?

I am happy to take a look at the IMDb CSV you have along with the log file to help diagnose (time permitting on my end of course).

**Comment by robme** [comment]
Hi, sorry for the delayed reply. Yes, I'm importing TV shows. It does say in the readme that it will import TV shows and episodes for IMDb, but it seems like maybe it only imports movies? Anyway, I have thousands of TV show ratings in my export from IMDb so not sure if this would ever work for me.

Anyway, I won't share all tens of thousands but here's the start of the export just in case
[imdb-ratings-excerpt.csv](https://github.com/user-attachments/files/16090183/imdb-ratings-excerpt.csv)

The log from that 
[small-log.log](https://github.com/user-attachments/files/16090194/small-log.log)

Thanks

**Comment by damienhaynes** [comment]
There was a change to IMDb csv files where tvseries and tvepisode types were renamed.
This should be fixed in 2.3.14.
