### ISSUE TITLE
Importing TV Shows from IMDB as Movies in Trakt

### ISSUE THREAD

**Issue by ikf7457** [damienhaynes/TraktRater#163]
Thanks for taking the time to create this tool. I just used it to import my watch list and ratings/history from IMBD (via csv export/import) and while the Movies have come across correctly, all the TV shows have been added as Movies. ie the tool (or Trakt) hasn't added the TV Shows, it's attempted to find Movies with the same name as the TV shows and it's added those instead. This has happened for both the watchlist and ratings/history. Did I miss something in the instructions? Is this expected behaviour or something not quite working as it should? Thanks.

**Comment by damienhaynes** [comment]
Thanks.

That is a strange result, do you mind sharing your CSV file? I can take a look to see if something has changed, in particular the identification of tv shows vs movies. If not, I can download my test one when I get a chance to take a look.

**Comment by ikf7457** [comment]
Hi,

Thanks for the quick reply.

I've attached the two .csv files.

I did try using the web scrape but that didn't work either, for ratings or watchlist, so maybe IMDB changed something on their side?

Thanks

Ian


________________________________

**Comment by damienhaynes** [comment]
Hi @ikf7457,

I did not get your attachments for some reason. However, I downloaded the latest csv exports for my login and did notice that there is a change. 

I will make a fix and let you know when available.

Cheers
Damien

**Comment by damienhaynes** [comment]
There may be more changes I haven't picked up on yet but the main thing is, is that they have renamed "tvepisode" to "tv episode" and "tvseries" to "tv series" ignoring the case.

So if you want to it to work with your current version you can do a mass rename in the csv's or just wait for an updated release.
