### ISSUE TITLE
IMDb to Trakt not working

### ISSUE THREAD

**Issue by ataberk1907** [damienhaynes/TraktRater#165]
[20240824_124333.log](https://github.com/user-attachments/files/16734213/20240824_124333.log)

**Comment by damienhaynes** [comment]
Can you please confirm what version of the app you are using and also copy some contents from your csv to this issue so I can inspect.

**Comment by ataberk1907** [comment]
v2.3.14 (Latest)

Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
1,tt0268978,2015-05-10,2015-05-10,,"A Beautiful Mind","A Beautiful Mind",https://www.imdb.com/title/tt0268978/,Movie,8.2,135,2001,"Biography, Drama, Mystery",997009,2002-01-04,"Ron Howard",,
2,tt0075686,2015-05-10,2015-05-10,,"Annie Hall","Annie Hall",https://www.imdb.com/title/tt0075686/,Movie,8.0,93,1977,"Comedy, Romance",280239,1977-04-20,"Woody Allen",,
3,tt2278388,2015-05-10,2015-05-10,,"The Grand Budapest Hotel","The Grand Budapest Hotel",https://www.imdb.com/title/tt2278388/,Movie,8.1,99,2014,"Adventure, Comedy, Crime",897583,2014-03-28,"Wes Anderson",,

**Comment by damienhaynes** [comment]
It appears there is something wrong with your downloaded CSV. You can see that the `Your Rating` column has no ratings.

Can you try downloading the csv file again.

**Comment by ataberk1907** [comment]
It is because the CSV is for my watchlist, I did not watch and rate them.

24 Ağu 2024 Cmt, saat 01:35 tarihinde Damien Haynes <
***@***.***> şunu yazdı:

**Comment by damienhaynes** [comment]
Thanks for confirming. I just tested by adding your contents to a test watchlist csv and it appeared to work:L
```
2024-08-24 09:48:19.530 [INFO] [][01]: Starting import from IMDb
2024-08-24 09:48:19.550 [INFO] [][01]: Reading IMDb ratings export...
2024-08-24 09:48:19.551 [INFO] [][01]: Reading IMDb watchlist export...
2024-08-24 09:48:19.592 [INFO] [][01]: Reading IMDb custom lists export...
2024-08-24 09:48:19.593 [INFO] [][03]: Found 0 movie ratings in CSV file
2024-08-24 09:48:19.593 [INFO] [][03]: Found 0 tv show ratings in CSV file
2024-08-24 09:48:19.593 [INFO] [][03]: Found 0 tv episode ratings in CSV file
2024-08-24 09:48:19.594 [INFO] [][03]: Found 0 movies in CSV file
2024-08-24 09:48:19.595 [INFO] [][03]: Found 3 movies watchlisted in CSV file
```
In the UI, are you only populating the watchlist text box and the rest are empty?

**Comment by ataberk1907** [comment]
Yes
![image](https://github.com/user-attachments/assets/7eb9b122-542b-4e66-a617-f92dacec4792)

**Comment by damienhaynes** [comment]
I may need your entire CSV if you are willing to share.

Also out of curiosity, what do you have set under your Windows Regional Settings? Is it an English locale?

**Comment by ataberk1907** [comment]
Yes I can share. No it is not an English locale, it is Turkish.

25 Ağu 2024 Paz, saat 01:01 tarihinde Damien Haynes <
***@***.***> şunu yazdı:

**Comment by damienhaynes** [comment]
Thanks for the additional info.

I believe the Turkish region is the issue (https://github.com/damienhaynes/TraktRater/issues/113)

Is it possible in the meantime for you to change the region to US, restart and try again? I haven't had a chance to address turkish region issue yet.

**Comment by damienhaynes** [comment]
Hi @ataberk1907, I have upgraded the CSV library I'm using. Can you please confirm if the issue is resolved using the attached update:

[TraktRater_v2.3.15.zip](https://github.com/user-attachments/files/16738778/TraktRater_v2.3.15.zip)

**Comment by ataberk1907** [comment]
Issue is resolved! Thanks for your help.

Damien Haynes ***@***.***>, 25 Ağu 2024 Paz, 04:37 tarihinde
şunu yazdı:
