### ISSUE TITLE
Login to Trakt not working

### ISSUE THREAD

**Issue by alexey-e-andreev** [damienhaynes/TraktRater#170]
Problem occured when I tried to import IMDb list, then I reset token and tried to connects to Trakt anew. Now I'm getting error again and again.

First time a got log:
>2024-09-27 15:06:51.967 [INFO] [][01]: Exchanging refresh-token for access-token...
>2024-09-27 15:06:51.972 [DEBG] [][03]: Address: http://api.trakt.tv/oauth/token, Post: {"client_id":"...","client_secret":"...","grant_type":"refresh_token","redirect_uri":"urn:ietf:wg:oauth:2.0:oob","refresh_token":"..."}
>2024-09-27 15:06:52.658 [ERR ] [][03]: Response: The remote server returned an error: (404) Not Found.
>2024-09-27 15:06:52.659 [ERR ] [][01]: Unable to login to trakt, check log for details

Now I got similar messages again and again:
>2024-09-30 09:33:51.830 [INFO] [][01]: Exchanging pin-code for access-token...
>2024-09-30 09:33:51.834 [DEBG] [][03]: Address: http://api.trakt.tv/oauth/token, Post: {"client_id":"...","client_secret":"...","code":"...","grant_type":"authorization_code","redirect_uri":"urn:ietf:wg:oauth:2.0:oob"}
>2024-09-30 09:33:56.214 [ERR ] [][03]: Response: The remote server returned an error: (404) Not Found.
>2024-09-30 09:33:56.215 [ERR ] [][01]: Unable to login to trakt, check log for details

**Comment by damienhaynes** [comment]
Thanks for reporting. I will fix this in a release coming this week.

**Comment by damienhaynes** [comment]
Fixed:
https://github.com/damienhaynes/TraktRater/releases/tag/2.3.15
