### ISSUE TITLE
Support for IMDb Custom Lists import

### ISSUE THREAD

**Issue by damienhaynes** [damienhaynes/TraktRater#25]

**Comment by dairefagan** [comment]
Thanks.

**Comment by damienhaynes** [comment]
The way it works currently:
* If the IMDb list does not exist in your user lists, then create a new list basis the filename
* If the IMDb list does exist in your user lists, then request the list and its items, then only send items (movies and shows) that are in the IMDb list that are not in the current trakt list. It does not do a delete of the list and re-create it.

Only deficiency with this approach is that if you want to remove items from your Trakt list as part of the sync, but I can make that option to also remove items from the list which do not exist in IMDb. That can be raised separately though.
