### ISSUE TITLE
Importing from Criticker: all ratings 1

### ISSUE THREAD

**Issue by DavidOliver** [damienhaynes/TraktRater#42]
Thanks for making TraktRater available!

A friend and I have both found that all movies rated/imported via TraktRater 2.2.0.0, Windows, end up rated as 1 at Trakt.tv.

I'm attaching the source XML and TraktRater log.

[ratings-david-outoften.xml.txt](https://github.com/damienhaynes/TraktRater/files/52934/ratings-david-outoften.xml.txt)

[20151205_070709.log.txt](https://github.com/damienhaynes/TraktRater/files/52935/20151205_070709.log.txt)

**Comment by DavidOliver** [comment]
Sorry - I now realise that's because we've scored them out of 10 at Criticker, where as TraktRater expects scores to be out of 100 as it divides by ten. I'll update our XML with XSLT.

**Comment by damienhaynes** [comment]
Is rating out of 10 an option on Criticker? The last time I checked the export file was out of 100 but didn't look into options.

**Comment by DavidOliver** [comment]
The Criticker XML export simply uses whatever numbers the user used, and users can use any number range they like as Criticker automatically infers tiers based on the range.

It might be better to use the 'tier' node, which is Criticker's interpretation of the user's score. On the other hand, the tier isn't an accurate representation of your score, and its value isn't always what you'd expect. So maybe it's best to state in the UI that score is expected be out of 100.

In case you want to give those who have scored out of ten or a smaller number some example XSLT to convert to out-of-100 scores:

    <?xml version="1.0" encoding="UTF-8"?>
    <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>

    <xsl:template match="score">
        <score>
          <xsl:value-of select=". * 10"/> 
        </score>
    </xsl:template>

    </xsl:stylesheet>

**Comment by damienhaynes** [comment]
Thanks for the info, I will look into enhancing next release.
