### ISSUE TITLE
Trakt login fails

### ISSUE THREAD

**Issue by dprtsk** [damienhaynes/TraktRater#45]
Getting the following error whether supplying my credentials, or a token:

Response: The remote server returned an error: (417) Expectation Failed.

**Comment by damienhaynes** [comment]
Are you by any chance going through a proxy server?

**Comment by dprtsk** [comment]
I do have a proxy installed, but it was deactivated. I'll see if I can find a machine without one at all.

**Comment by dprtsk** [comment]
Works okay from a machine without proxy software. Sorry for the false alarm, feel free to close the issue.

Thanks for the software!

**Comment by damienhaynes** [comment]
That's okay, I think there is a way to prevent this issue in a .Net application by setting:
``
System.Net.ServicePointManager.Expect100Continue = false;
``

I'll leave this open for consideration in next release.

**Comment by gadour97** [comment]
i get a message : login failed every time
i don't use any proxy but i didn"t find any textbox to put my code
