### ISSUE TITLE
Support for import from Flixster

### ISSUE THREAD

**Issue by 8va** [damienhaynes/TraktRater#52]
Would this be a possibility? That's the site I've used over the years, and it drives me crazy. Would truly appreciate this implementation.

Thanks for considering :)

**Comment by damienhaynes** [comment]
Yes I probably can do it via there API e.g.

http://www.flixster.com/api/users/$userid/movies/ratings?scoreTypes=numeric&page=1&limit=10

Where $userid is your user id. I could ask for input of that then handle everything automagically

**Comment by 8va** [comment]
it's like you're a super hacker hero.
man, I seriously thank you for lending your time and skills.
I have that list with my user id now. I wonder if I could get it to you privately, however? (my name is all over it in the data, and sometimes I'm a little more paranoid than average.)

**Comment by damienhaynes** [comment]
That's alright, its pretty easy for me to build up a list of rated movies to test with.

**Comment by 8va** [comment]
super hacker hero. 🙏🏻

**Comment by damienhaynes** [comment]
it seems flixster contains ratings from a few sources like facebook and rotten tomatoes as well :)

**Comment by damienhaynes** [comment]
I will give you a test build to play with soon.

**Comment by damienhaynes** [comment]
You can test support for Flixster from here:
https://dl.dropboxusercontent.com/u/10516352/trakt/TraktRater.exe

**Comment by 8va** [comment]
First of all -- again, thank you so much.

I can't believe it, but it looks like Flixster _just_ took away their social features and profiles from online. Looks like website is just a landing page for Fandango and the Flixster mobile app now. I was still able to grab my user ID through my browser history, but the import didn't work -- I'm guessing because the profile page doesn't exist on the web anymore, including that API page. My profile and data/ratings are still there on my iOS Flixster app though.

Do you think there's any way around this?

**Comment by damienhaynes** [comment]
Wow! How frustrating. 

Hopefully adding support wasn't a waste of time,

**Comment by damienhaynes** [comment]
And yes, I used the LastUpdated field to determine when something was rated. Although, it was not 100% exact as it just returned something like '1 Day Ago' or '5 Years Ago'.

**Comment by 8va** [comment]
Ahh, Flixster is back up again! I was able to successfully import my ratings into Trakt. This is fantastic, thank you!!
If I may, I have a couple questions:
- Is there any way to pinpoint which films weren't able to transfer? (ie. I have 218 ratings on Flixster -- 204 of them transferred successfully to my ratings, and 205 transferred to my History.)
- I'm already so grateful and don't want to push it, but would it be very easy to also add functionality to transfer my Flixster "Want to See" list to my Trakt Watchlist?

**Comment by damienhaynes** [comment]
You can check the log, it has details on what movies were not found on trakt. Search for "not_found".

I can look at also supporting Want to See. If the request method is there then should be no problem.

**Comment by damienhaynes** [comment]
Here is a new build with wanttosee sync to watchlist:

https://dl.dropboxusercontent.com/u/10516352/trakt/TraktRater.exe

**Comment by damienhaynes** [comment]
No problem.

It will detect what you have already rated, watched, watchlisted and only send the difference.

**Comment by damienhaynes** [comment]
I've made a pre-release available: https://github.com/damienhaynes/TraktRater/releases/tag/2.2.2
