### ISSUE TITLE
Flixster:Sequence contains no elements

### ISSUE THREAD

**Issue by hitesh7k** [damienhaynes/TraktRater#54]
Tried TrakRater 2.2.2.1. It imported successfully 800+ Ratings (total 15 Pages, (by Logfile)). But Trakt.tv is not updating imported movie rating.

This is what I did,
Authorised PIN Code for Trakt.
Given Flixter User ID.
Log file showing 13 pages of rating imported successfully.

But, Trakt.tv is showing nothing new.

Logfile is attached.
[20160802_043335.zip](https://github.com/damienhaynes/TraktRater/files/398634/20160802_043335.zip)

**Comment by damienhaynes** [comment]
Thanks, looks like an error generated when retrieving from Flixster, this would explain why you saw nothing on trakt as it does the import after that.

I will take a closer look and see why that error is occurring.

**Comment by damienhaynes** [comment]
Issue has been fixed:
https://github.com/damienhaynes/TraktRater/releases/tag/2.2.3
