### ISSUE TITLE
Import from Flixter in version 2.2.3

### ISSUE THREAD

**Issue by hitesh7k** [damienhaynes/TraktRater#56]
I have 862 movies in Flixter. 
Version 2.2.3 of TrakRater was able to pull 562 Movies in total. 
Now I have total 620 movies rated in Trakt.tv. 
Approximately 300 Movies are missing.
Can you look at the log files ? I have tried multiple times.
[Logs.zip](https://github.com/damienhaynes/TraktRater/files/401292/Logs.zip)

**Comment by damienhaynes** [comment]
When getting movies online from your Flixster account it only finds 600. Out of those 600 movies, you have 562 which have ratings. 38 of these movies do not import into trakt because Flixster does not have IDs for movies so it relies on Title + Year which must be exactly the same on both sites, this is not the case im afraid so there is nothing I can do about that.

You say you have 862 movies on Flixster, I'll take another look but there might be a limitation of 600 that I can get.

**Comment by damienhaynes** [comment]
Actually, I think it might be another error that limited me seeing 600. But as I said there will be some which fail due to the title+year matching, definitely not 300 though!

**Comment by damienhaynes** [comment]
Found the problem, its the response from Flixster which is bad:

    "movie": {
      "id": 770740157,
      "title": "Iron Man 2",
      "year": "",
      "synopsis": "",
      "url": "http:\/\/www.flixster.com\/movie\/iron-man-2\/",
      "vanity": "iron-man-2",
      "movietype": "Other",
      "poster": {
        "thumbnail": "http:\/\/d2g793j3cnxk76.cloudfront.net\/static\/images\/movie.none.tmb.gif",
        "mobile": "http:\/\/d2g793j3cnxk76.cloudfront.net\/static\/images\/movie.none.tmb.gif",
        "profile": "http:\/\/d2g793j3cnxk76.cloudfront.net\/static\/images\/movie.none.pro.gif",
        "detailed": "http:\/\/d2g793j3cnxk76.cloudfront.net\/static\/images\/movie.none.det.gif",
        "320X480": "http:\/\/d2g793j3cnxk76.cloudfront.net\/static\/images\/movie.none.det.gif"
      },
      "audienceScore": 54,
      "mpaa": "Unrated",
      "affiliate": {
        
      },
      "playbackAvailable": "",
      "storeAvailable": ""
    },

the Year is not a valid integer type.

**Comment by damienhaynes** [comment]
It now should find 960 movies from your Flixster account of which 862 have ratings.

**Comment by damienhaynes** [comment]
https://github.com/damienhaynes/TraktRater/releases/tag/2.2.4

**Comment by hitesh7k** [comment]
I have now 900 Movies rated on trakt.tv ... Thanks
