### ISSUE TITLE
Authorizing Trakt

### ISSUE THREAD

**Issue by erinrachael86** [damienhaynes/TraktRater#58]
Hi, this may be a stupid question, but where do I put in the authorization code when trying to get traktrater authorized for my account. The instructions just indicate to put the activation code "in the box provided" but there isn't one...

I'm getting a log in error when I try to import my ratings and I'm assuming it's because the account isn't authorized. Can  you clarify for me?

Thanks!
![traktrater](https://cloud.githubusercontent.com/assets/24623197/21287544/234a7f0c-c43c-11e6-9a18-618c03dbb932.jpg)

**Comment by damienhaynes** [comment]
You need to download the latest release, that one is pretty old.

https://github.com/damienhaynes/TraktRater/releases
