### ISSUE TITLE
No sites enabled or incorrect site information supplied!

### ISSUE THREAD

**Issue by xbmcnut** [damienhaynes/TraktRater#61]
Can't login to Trakt with either pin code or username/password. The log says `2017-02-23 19:22:31.343 [ERR ] [][01]: No sites enabled or incorrect site information supplied!` when I click the import button. Windows 10, DotNet 4.0 preinstalled.

Tried 2.2.3 and 2.2.4.

**Comment by damienhaynes** [comment]
It seems you haven't enabled anything to import, check the state of the 'Enabled' checkboxes as the application will abort if there is nothing selected to import.
