### ISSUE TITLE
Export from Trakt

### ISSUE THREAD

**Issue by dairefagan** [damienhaynes/TraktRater#64]
Can you please implement a feature to export custom lists from Trakt? This is currently a VIP feature and you have to sign a subscription for a year if you just want to do this.

**Comment by damienhaynes** [comment]
Sounds like a good idea, and not hard to implement.

**Comment by damienhaynes** [comment]
Im going to start working on an export to CSV feature now, when complete it shall pull down all user data from trakt.tv (basis what you want) and create CSV files e.g. watched_episodes.csv, watched_movies.csv etc.

**Comment by damienhaynes** [comment]
This is now done.
