### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by lucfig** [damienhaynes/TraktRater#67]
Hi,

For any operation I try, I receive the following error in the log:
Response: O servidor remoto retornou um erro: (500) Erro Interno do Servidor

In English is something like:
Response: The server returned an error: (500) Internal server error.

I believe TraktRater isn't able to connect with Trakt. I tried cleanup/maintenance and imdb import via both CSV and Web scrape. Also tested with user/pass and pin code authentication methods.

Is there any more info I can provide?

Regards,

EDIT1:  It seems my lists were too large and could not be parsed in only one attempt. After trying a couple more times, all my movies were updated. Thank you!

**Comment by damienhaynes** [comment]
Good to hear,
