### ISSUE TITLE
added iCheckMovie support (Pull Request ready for review)

### ISSUE THREAD

**Issue by glenngr** [damienhaynes/TraktRater#70]
https://github.com/damienhaynes/TraktRater/pull/69

I added a feature for importing movies from iCheckMovies. Take a look at the PR :)

**Comment by damienhaynes** [comment]
One other thing that can be checked before import is to only send to trakt items that don't exist e.g. pull down watched history from trakt.tv and only insert new items. Doing this avoids getting an extra play count.
