### ISSUE TITLE
IMDb Rating Import error  (CSV has changed from expected format)

### ISSUE THREAD

**Issue by brewster1134** [damienhaynes/TraktRater#71]
When I go to import IMDB ratings from a csv file, I get the error: `IMDB: the given key is not present in the dictionary`

the ratings csv differs from the watchlist csv (which imported successfully). but just in case, the headers for the ratings csv are:
```
Const | Your Rating | Date Added | Title | Title Type | Directors | IMDb Rating | Runtime (mins) | Year | Genres | Num Votes
```

the error log simply shows:
```
2017-11-08 18:43:39.028 [INFO] [][01]: Starting import from IMDb
2017-11-08 18:43:39.040 [INFO] [][01]: Reading IMDb ratings export...
2017-11-08 18:43:39.214 [INFO] [][01]: Reading IMDb watchlist export...
2017-11-08 18:43:39.217 [INFO] [][01]: Reading IMDb custom lists export...
2017-11-08 18:43:39.220 [ERR ] [][01]: IMDb:The given key was not present in the dictionary.
2017-11-08 18:43:44.229 [INFO] [][01]: Finished import from IMDb
2017-11-08 18:43:44.398 [INFO] [][01]: Import Complete!
```

**Comment by damienhaynes** [comment]
This is what mine looks like:
"position","const","created","modified","description","Title","Title type","Directors","You rated","IMDb Rating","Runtime (mins)","Year","Genres","Num. Votes","Release Date (month/day/year)","URL"

I just went to IMDb and tried to download my CSV again but I can no longer find the option! Do you know where the link has gone?

**Comment by brewster1134** [comment]
Yeah it took me awhile to find it too :/ Only for the ratings list, it's now at the top of the page, under the menu with the 3 dots icon

**Comment by damienhaynes** [comment]
Cool, found it. Also confirmed the headers have changed now so will need to provide an update.

Stay tuned.

**Comment by damienhaynes** [comment]
In the meantime, you could rename your columns as per my example

**Comment by brewster1134** [comment]
so i modified the csv file, however according to the logs, TraktRater seems to be trying to scrape IMDB instead of using the csv file. i have tried unsetting it and setting i back, and restarting it, but it seems to be stuck on wanting to use the Web Scrape option...

**Comment by damienhaynes** [comment]
That seems very odd, I have never encountered that. You could also try deleting your configuration file that persists the settings at 'C:\Users\<username>\AppData\Roaming\TraktRater

**Comment by brewster1134** [comment]
using mono/mac :)

**Comment by damienhaynes** [comment]
I see, then I would not have a clue off the top of my head. Try search for Settings.xml on disk. 

Either way sounds like a bug somewhere and probably due to Mono/Mac usage. Sounds like a seperate issue though.

**Comment by damienhaynes** [comment]
Whats really annoying is that they are using the old format still on Watchlist exports.

**Comment by audiosavas** [comment]
Hi, could anyone help on how to convert the new ratings .csv so that TraktRater reads it?

**Comment by damienhaynes** [comment]
I will probably making a new release this weekend, I have made changes to support both formats.

**Comment by damienhaynes** [comment]
wow, it looks like the ratings.csv format has reverted back to old style. Can anyone confirm?

**Comment by brewster1134** [comment]
haha yea they are messing with us! confirmed...

**Comment by damienhaynes** [comment]
I'll probably hold off the release for a while if its back to a working state. I will keep an eye on any future changes over the next few weeks but it sounds like they realise it was a bad idea to change it.

**Comment by Kenifornication** [comment]
It's broken again!

**Comment by tachav** [comment]
same error when trying to import imdb watchlist, not ratings. Can you please give an example of your watchlist.csv so i can modify it until next release? thanks in advance

**Comment by Lishen23** [comment]
I'm having the same issues with custom lists, does anyone know the format that custom lists need to be in?

**Comment by damienhaynes** [comment]
#75 addresses the CSV format change from IMDb.
