### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by cmaciasjimenez** [damienhaynes/TraktRater#76]
Hi, I'm trying to sync my IMDB ratings with trakt as I've always done in the past. This time when doing the import of my .csv file exported from IMDB I'm getting a red status message stating "IMDB: The given key was not present in the dictionary". When finished It seems the import didn't work since my trakt profile doesn't reflect the new scores. Can you help me?

Thank you.
![screenshot 2018-01-01 23 12 29](https://user-images.githubusercontent.com/1439317/34471433-bc8ffbcc-ef49-11e7-91a7-6c2e98a7e91b.png)

**Comment by damienhaynes** [comment]
There was a recent change on IMDb with their CSV format. This has now been fixed and there will be a new release shortly that you can use.
