### ISSUE TITLE
Importing from Letterboxd error

### ISSUE THREAD

**Issue by eliehaykal** [damienhaynes/TraktRater#78]
Is anyone able to import from Letterboxd?
When I attempt to import using a "watched.csv" file, I get the below:

> 2018-01-02 17:54:42.106 [INFO] [][01]: Logging in to trakt.tv...
> 2018-01-02 17:54:42.582 [DEBG] [][06]: Response: {"token":"ZPzzPUQW39wxdnaw4FRL"}
> 2018-01-02 17:54:42.583 [INFO] [][01]: Starting import from Letterboxd
> 2018-01-02 17:54:42.584 [INFO] [][01]: Reading Letterboxd ratings export...
> 2018-01-02 17:54:42.584 [INFO] [][01]: Reading Letterboxd watched export...
> 2018-01-02 17:54:42.585 [INFO] [][01]: Reading Letterboxd diary export...
> 2018-01-02 17:54:42.585 [INFO] [][06]: Found 0 movie ratings in CSV file
> 2018-01-02 17:54:42.586 [INFO] [][01]: Requesting watched movies from trakt...
> 2018-01-02 17:54:42.586 [DEBG] [][06]: Address: http://api.trakt.tv/sync/watched/movies
> 2018-01-02 17:54:42.837 [ERR ] [][06]: Response: The remote server returned an error: (401) Unauthorized.
> 2018-01-02 17:54:42.838 [INFO] [][01]: Found 0 watched movies on trakt
> 2018-01-02 17:54:42.839 [INFO] [][01]: Filtering out watched movies that are already watched on trakt.tv
> 2018-01-02 17:54:42.839 [INFO] [][01]: Importing 27 Letterboxd movies as watched...
> 2018-01-02 17:54:42.840 [INFO] [][01]: Importing page 1/1 Letterboxd movies as watched...
> 2018-01-02 17:54:42.840 [DEBG] [][06]: Address: http://api.trakt.tv/sync/history, Post: {"movies":[{"ids":null,"title":"The Dark Knight","year":2008,"watched_at":"2015-11-14T00:00:00Z"},.....{"ids":null,"title":"Down Terrace","year":2009,"watched_at":"2018-01-03T00:00:00Z"},{"ids":null,"title":"Dr. No","year":1962,"watched_at":"2018-01-03T00:00:00Z"}]}
> 2018-01-02 17:54:43.162 [ERR ] [][06]: Response: The remote server returned an error: (401) Unauthorized.
> 2018-01-02 17:54:43.162 [ERR ] [][01]: Failed to send watched status for Letterboxd movies to trakt.tv
> 2018-01-02 17:54:45.162 [INFO] [][01]: Finished import from Letterboxd
> 2018-01-02 17:54:45.185 [INFO] [][01]: Import Complete!

**Comment by damienhaynes** [comment]
Try to re-authorise the application, select Pin-Code method if  you are using Username/Password option.

**Comment by eliehaykal** [comment]
Worked with Pin-Code.
Thanks
