### ISSUE TITLE
[??] Import Title;year files

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [damienhaynes/TraktRater#86]
Can i import a normal title year csv/xlsx like this one:
![image](https://user-images.githubusercontent.com/38154154/38453273-7b6239fe-3a70-11e8-8e89-25a7655efccd.png)

![image](https://user-images.githubusercontent.com/38154154/38453278-928f378a-3a70-11e8-982e-61af7597f251.png)

**Comment by damienhaynes** [comment]
I want to create a custom import from CSV, which will cover this requirement.

**Comment by damienhaynes** [comment]
This will be covered by #13 .
