### ISSUE TITLE
"Watched Date" field not importing from letterboxd

### ISSUE THREAD

**Issue by digi10** [damienhaynes/TraktRater#87]
Hi,
First, thanks for creating this utility - very useful!  
I'm trying to import into Trakt a short test movie list (10 films) that I exported from letterboxd, but TraktRater doesn't appear to be setting the Trakt Watched Date properly.  I've tried this several ways, even going into the letterboxd CSV export files and changing the Date field (normally set to export date) in the CSV files to match the Watched Date field in the Diary CSV, but it still isn't working.  As a further test, in TraktRater options I turned on the third checkbox (set Watched Date to Release Date if the Watched Date is not available in export), and this DOES result in Watched Date = Release Date in Trakt.  So this is telling me that the parser is not correctly finding the Watched Date data in the CSV files coming from letterboxd, even though they are there.  I hope you can take a look into this and make a quick fix!
Many thanks!

**Comment by damienhaynes** [comment]
Hi,

This was by design, it will import the watched date if it exists. This comes from the Diary file if you export that from Letterboxd and configure that file in TraktRater.

I can see the first column in the Ratings/Watched csvs have a Date column, but these don't really mean the date you watched the film. I could add an option to process it though easy enough.

**Comment by damienhaynes** [comment]
Are you importing the Diary file with the Watched file? Because I will only process the watched date from the Diary file?

**Comment by digi10** [comment]
[baseline.zip](https://github.com/damienhaynes/TraktRater/files/1935106/baseline.zip)
Hi Damien,
Thanks for the quick response!  I actually tried it both of the following ways with the same result:
1.  Import with all three file paths set:  watched, diary, ratings.
2.  Import with only the diary path filled in.
In both cases, the Trakt Watched date was not filled in properly.  I'm attaching the three sample files I've been using.

**Comment by damienhaynes** [comment]
Just reading the code again, what should happen is this:

* If 'Watched Date' exists use that;
* Otherwise use 'Release Date' if corresponding configuration is set;
* Otherwise use 'Date' field.

There could be a bug, but need to double check that is not what you see first.

**Comment by damienhaynes** [comment]
Thanks, just from a quick inspection it looks like your date format is MM-DD-YYYY where the program was expecting DD-MM-YYYY. This might very well be the reason its not working. Will double check and fix if that is the case.

**Comment by damienhaynes** [comment]
That was indeed the problem, I will make a fix to better support different date formats. I didn't expect the CSV export from their site to use different formats.

**Comment by damienhaynes** [comment]
Please use new release:
https://github.com/damienhaynes/TraktRater/releases/download/2.3.3/TraktRater_v2.3.3.exe

**Comment by digi10** [comment]
Thanks for the lightning fast update Damien!  I will try this out ASAP and report back on how the new version works.

**Comment by digi10** [comment]
Damien,
Sorry it took so long to get back to you on this!  Thanks for making the update.  Importing from letterboxd with "Watched Date" format of MM/DD/YYYY is basically working now.  The only odd thing I notice is that it is setting the Trakt watch date to 1 day earlier than what is in the letterboxd csv file.  For example,  a letterboxd watched date of 12/30/2017 is showing up in Trakt as 12/29/2017.  This is consistent for every title I import in the test file I sent to you earlier.

**Comment by damienhaynes** [comment]
When I send the watched date over the API, its done in UTC (I do not convert, as I do not know what the timezone is in the csv file). The date time shown on trakt will presumably in your local time which is defined in https://trakt.tv/settings.

Do you know what time-zone the CSV dates are using?

**Comment by digi10** [comment]
Ok, yes - that is the issue.  Thanks again for the help!
