### ISSUE TITLE
iCheckMovies:Fields 'CheckedCount' do not exist in the CSV file

### ISSUE THREAD

**Issue by oavaldezi** [damienhaynes/TraktRater#89]
I'm using the [iCheckMovies Enhanced script](https://github.com/labyrinthofdreams/icm-enhanced) to download my checked movies to CSV files. 
A [sample](https://github.com/damienhaynes/TraktRater/files/1964727/Your.checked.movies.-.page.18.txt) with extension changed to TXT is attached.

When I try to upload them with TraktRater, the logs show this error: "iCheckMovies:Fields 'CheckedCount' do not exist in the CSV file".

**Comment by damienhaynes** [comment]
Can you download your CSV from the iCheckMovies site?

**Comment by oavaldezi** [comment]
I don't have a paid account, so I'm 'm using the [iCheckMovies Enhanced script](https://github.com/labyrinthofdreams/icm-enhanced).
What fields and headers does TraktRater expect? I could manually fix the CSV download to suit Trakt rater.

**Comment by damienhaynes** [comment]
Fields it expects are:

Title
Year
CheckedCount
FavouriteCount
UserToplistCount
OfficialToplistCount
AkaTitle
ImdbUrl
Checked
Favorite
Disliked
Watchlist
Owned

**Comment by oavaldezi** [comment]
Thanks. I'll give it a try.

**Comment by oavaldezi** [comment]
Unfortunately, it didn't work. The [log file](https://github.com/damienhaynes/TraktRater/files/1965442/20180501_050015.txt)  is attached. The error this time was "iCheckMovies:The conversion cannot be performed." 
My CSV file didn't include CheckedCount, FavouriteCount and UserToplistCount data, so I set them all to '1'.
The CSV file header and first data rows look like this:
Title,Year,CheckedCount,FavouriteCount,UserToplistCount,OfficialToplistCount,AkaTitle,ImdbUrl,Checked,Favorite,Disliked,Watchlist,Owned
The Shop Around the Corner,1940,1,1,1,12,,http://www.imdb.com/title/tt0033045/,yes,yes,no,no,no

Any suggestions (apart from getting a paid account, which I might)?

**Comment by damienhaynes** [comment]
I've attached a sample file I got from a paying member.

[checked.zip](https://github.com/damienhaynes/TraktRater/files/1965508/checked.zip)

On thing that is not obvious, if the movie is watched, ensure that the column holds the date it was watched.

**Comment by oavaldezi** [comment]
Thank you for your help. There's other data I'm not getting from my (unpaid) CSV download, such as icheckmovies.com URLs.

Oh, well. It's an inexpensive subscription. I'll see if I can make it work with one.

Thanks again.

BTW, and OT, I found this [script](https://pynej.blogspot.com/2017/07/netflix-to-trakttv-sync.html) to sync Netflix to Trakt.tv

**Comment by damienhaynes** [comment]
No worries, I don't think you need to populate the icheckmovies url, only the imdb one as thats all the application needs to get a good match on trakt.tv.
