### ISSUE TITLE
Enhancement request  to the maintenance feature: Remove Resume States.

### ISSUE THREAD

**Issue by phatboyj** [damienhaynes/TraktRater#96]
@damienhaynes 

I'm not sure you're still active on this project, but here's hoping.

I would love to see an addition to the Maintenance section for Removing Resume States "sometimes referred to as Trakt Bookmarks" for Episodes, and Movies. currently I know of no way to do this, but this feature would be huge for Kodi users, as some add_ons provide what they call Trakt On Deck for playing episodes and Movies from said resume states by populating a list of uncompleted Episodes, and movies from the Trakt Bookmark data, but for some reason my list has been over populated with bogus entries and there is currently no way to resolve this issue.

**Comment by damienhaynes** [comment]
Good idea, I think this would very useful. I will try implement this very soon.

**Comment by phatboyj** [comment]
Awesome @damienhaynes
Quick Newb ?
What is the syntax for adding a Label to the subject line for issues  for example the Enhancement Label?

I did find where @sharkykh  implemented this feature as a  Python script called ["TraktPlaybackProgressManager"](https://sharkykh.github.io/TraktPlaybackProgressManager/) But I'm at a loss as how to use it, do to my lack of understanding and vague install instructions.  Maybe his code will help you in implementing it into your application.

Thanks for your work on this and for taking my suggestion seriously Your App is a life saver for when you need it you absolutely need it!

**Comment by damienhaynes** [comment]
The label options are on the RHS menu, it's possible only myself can see it.

![image](https://user-images.githubusercontent.com/680624/56074175-27569d00-5df1-11e9-86a8-127b917d3ef7.png)

**Comment by damienhaynes** [comment]
[TraktRater_v2.3.5.zip](https://github.com/damienhaynes/TraktRater/files/3075837/TraktRater_v2.3.5.zip)
@phatboyj, find attached maintenance options to clear paused states.

**Comment by phatboyj** [comment]
@damienhaynes
Thanks for this I will give it a try

And yes the Trakt add_on for Kodi is designed to auto sync changes to the kodi library.  My next challenge is to get the Author of that add_on to incorporate this feature, thus making things easier for all kodi users.

I'll post back as soon as I have time to test Thanks a million for your efforts

**Comment by damienhaynes** [comment]
I've made the release official now including support to export all your data to csv files.
