### ISSUE TITLE
How to trigger the new Trakt Export to .csv

### ISSUE THREAD

**Issue by phatboyj** [damienhaynes/TraktRater#98]
I was attempting to try the new Export feature but I can only seem to select what I want to export and where but have no way to actually trigger the feature.

Is there a hidden button somewhere? What am I missing here? 

**EDIT:**
I finally figured out that if I put a check in the check box for the desired task and then select close x in the top right hand corner then re enter the csv export menu then place my mouse focus on something other than what is selected and then press the enter button on my keyboard it triggers the desired task/tasks

I'm not sure if this was your intended use case, but it's the only way I can get the task to trigger on windows 10 I'm running the .exe strait from my desktop

**Comment by damienhaynes** [comment]
That's very odd!

So you don't see the 'Start Export' button on bottom right hand corner?

![image](https://user-images.githubusercontent.com/680624/61600092-395a9e00-ac72-11e9-9a93-35f9efb92170.png)

**Comment by phatboyj** [comment]
Nope My screen cuts off directly under the Export Path Box.
I tried to resize the window but the option is greyed out, also moving the window around didn't help either.

I originaly had an earlier version of 2.3.5 installed as it didn't show the export feature at all so I installed the latest after reading about the added feature, and this is where I'm at. 

Otherwise the Export feature seems to work Well with the exception of the custom list export.
I have a total of 21 custom lists 
all 21 get exported but several of them end up with 0 sized files.
I do have a couple of lists that are empty but the ones that I'm worried about are not and should not produce 0bit files "obviously"

So an enhancement may be necessary.
One that would allow for the end -user to input the name of the desired custom list and export them one at a time.
Just my thoughts on the matter.
As with all things it gets better with time.

Thanks for the attention.

**Comment by damienhaynes** [comment]
Okay, sounds like I need to fix the UI to work with different screen resolution/font dpi as well as fix what is not working with your custom list export.

Any chance you can provide a link to one of your lists that are not working? You will need to make it public, then I can clone it and see why it's not working.

Cheers

**Comment by phatboyj** [comment]
Yep No prob

**Comment by damienhaynes** [comment]
Also, can you can you let me know what screen resolution you are running and what your DPI is set to e.g. 100%, 150% ? I just tried a few options and can not reproduce the buttons being cut off.

**Comment by phatboyj** [comment]
Yep

Res=
1366 x  768 (Recommended) as it's the native Res
And
Scale And Layout=
125%

Orientation=
Landscape

Export Files attached as a .zip including a ReadMe
 
[0bite_CustomList_Files_and_ReadMe.zip](https://github.com/damienhaynes/TraktRater/files/3415697/0bite_CustomList_Files_and_ReadMe.zip)

**Comment by damienhaynes** [comment]
Thanks for the information, I've not tested that low of a resolution with a scaling set beyond 100%. You might have some luck at 100% but I will investigate.

I cloned all your public lists and successfully exported them (see attached). Could you attach your log after attempting to export please? I may be able to spot something in there that is causing the error.

**Comment by damienhaynes** [comment]
I can reproduce the UI issues with your 1366x768 and 125% scaling, I will see what I can do to resolve the issue. 

If you have another computer in the meantime with higher resolution, then it might be a good work around in the meantime.

**Comment by phatboyj** [comment]
Sorry Boss No Logs for You

They all Exported this time.  The Only Empty files I have Should be Empty.  On a side Note, a couple of them still have the # strings appended, but, I beleive that has something to do with them being cloned Lists, or having originated as a cloned list.

Here's a Pic for you instead.  I'll try at 100% and see if it makes a difference

While I have your attention,
any ideas on how I can remedy the problem I have with My Trakt Library being combined with my Wifes 
I mentioned this in another thread but while I have you here I figured why not ask

The prob being I can easily remove the shows that she doesn't watch but I do But that leaves a rating behind for every Episode of every show that is removed and simply Unrateing every episode by hand will take me Days?

Thanks for all your help

![No_Buttons_TraktRater_Options_Screen](https://user-images.githubusercontent.com/1485513/61607628-9d06ac00-ac1d-11e9-82e9-96d1b621fed0.jpg)

**Comment by damienhaynes** [comment]
I think those # strings are due to them existing online as part of the slug ID which is suppose to be a unique name (perhaps you had a duplicate named list at some point and hence why trakt automatically added it). I use the slug as its safe to use as a filename.

Sorry, I'm not sure about the best way to deal with your library issue. I guess once I create an import feature from csv it will make it easier to simply edit the rating file.

**Comment by phatboyj** [comment]
Thanks anyway I did try at 100% and the buttons appear and also it made me realize that I was missing buttons from other pages as well even at 1oo% the Status section at the bottom of the options page is partially cut off but at 125% I didn't even know it existed LOL

as for as my library issue gos I'll just Blow hers out all together as her Kodi Library is unaffected.
Meaning it never got synced to the bad trakt so I should be able to add each show to the Watch list one at a time from her Kodi Library after blowing Trakt out completely Not Ideal But better than the alternative atleast she only has 150 shows to my 400+ 


Thanks for looking into this  at the rate you're going with this,  your app is going to offer more functionality than you get with a VIP sub from Trakt hell you may already be at that point.

I'll let you close this when you feel it's resolve until then let me know if you need any testing via my ancient stone tablet.
